author: croxis
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.croxis.plugins.lift.BukkitLift
name: Lift
startup: postworld
version: ${version}
description: ${project.description}
softdepend: [Spout,AntiCheat,NoCheatPlus]
permissions:
  lift:
    description: Can ride in a lift
    default: true
  lift.change:
    description: Can change lift floors
    default: true
commands:
   lift:
      description: Scans a lift.
      usage: /<command>
      permission: lift
      permission-message: You don't have lift permissions
